# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a74ab8d2be7254c8621c5bc8ddef13424bf8426aad2df8e9764202f3abc2369416c9bf9b93f290d0b6276b7f930d1a69a2d8ae6e767e63295772e7513c5d9b0e

test:
  secret_key_base: d3d9e9a4f71fe4cfc2856a6cf7f1f31e5c01e62963710cd74d68d01a014e40600c5b0e6ee4663fab06b0734ceef6dbdc1395bfba726ee76b2d1b44ebc67ee528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
